FROM ssh-base:1.0 AS ssh-environment

FROM nvim-node:0.10.4-node20

# 建立 SSH 目錄結構
RUN mkdir -p /etc/ssh && \
    mkdir -p /root/.ssh && \
    chmod 700 /root/.ssh

WORKDIR /workspace

CMD ["/bin/bash"]